### ISSUE TITLE
Instructions for building from source

### ISSUE THREAD

**Issue by JoelMon** [01CodeLT/meeting-display#3]
Hello brother!

Would it be possible to add instructions for building from source? I'm not too familiar with JavaScript/Typescript build's processes (Linux). I'm going to have to start learning a bit of Typescript since most projects brothers are sharing is in TS. lol

Aslo, if I figure it out in the next few hours would it be ok if I PR the instructions?

Thanks

**Comment by 01CodeLT** [comment]
Hi brother,
I apologise for the late response. To run the app during development you need to run both the angular and electron processes in two separate terminals using...
`npm run ng:serve`
`npm run electron:serve`

To build the app you'll have to add a file named electron-builder.yml in the root directory with the following content
```productName: "Meeting Display"
appId: "com.01coding.MeetingDisplay"
publish:
  provider: "github"
  url: "https://github.com/01CodeLT/meeting-display.git"
  token: "PUBLISHING_TOKEN"
  channel: "latest"
files: [
  "**/*",
  "!**/*.ts",
  "dist/**/*",
  "!*.code-workspace",
  "!LICENSE.md",
  "!package.json",
  "!package-lock.json",
  "!src/",
  "!e2e/",
  "!hooks/",
  "!angular.json",
  "!_config.yml",
  "!karma.conf.js",
  "!tsconfig.json",
  "!tslint.json"
]
win:
  icon: "icon.ico"
  target: [
    "portable", "nsis"
  ]
mac:
  icon: "icon.icns"
  target: ["dmg"]
```

Then you can build the app with the command...
`npm run electron:build`

The application will build to a folder named dist which will create both an installable and portable version of the app.

Hope this helps, let me know if you have any issues 👍
